/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Senoramadhani
 */
public class Master extends javax.swing.JFrame {
    
    
    public Master() {
        initComponents();
        tgljam();

    }
    public void tgljam(){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblagama = new javax.swing.JLabel();
        lblpekerjaan = new javax.swing.JLabel();
        lbldesa = new javax.swing.JLabel();
        lblpetugas = new javax.swing.JLabel();
        lblshdrt = new javax.swing.JLabel();
        lblmenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        getContentPane().setLayout(null);

        lblagama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agama.png"))); // NOI18N
        lblagama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblagamaMouseClicked(evt);
            }
        });
        getContentPane().add(lblagama);
        lblagama.setBounds(20, 120, 150, 53);

        lblpekerjaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pekerjaan.png"))); // NOI18N
        lblpekerjaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpekerjaanMouseClicked(evt);
            }
        });
        getContentPane().add(lblpekerjaan);
        lblpekerjaan.setBounds(370, 120, 150, 50);

        lbldesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/desa.png"))); // NOI18N
        lbldesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldesaMouseClicked(evt);
            }
        });
        getContentPane().add(lbldesa);
        lbldesa.setBounds(200, 120, 150, 50);

        lblpetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/petugas.png"))); // NOI18N
        lblpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpetugasMouseClicked(evt);
            }
        });
        getContentPane().add(lblpetugas);
        lblpetugas.setBounds(20, 210, 150, 50);

        lblshdrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/shdrt.png"))); // NOI18N
        lblshdrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblshdrtMouseClicked(evt);
            }
        });
        getContentPane().add(lblshdrt);
        lblshdrt.setBounds(370, 210, 150, 50);

        lblmenu.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmenu.setText("Data Master");
        getContentPane().add(lblmenu);
        lblmenu.setBounds(0, 10, 540, 42);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Kembali ke Menu");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 100, 15);

        setSize(new java.awt.Dimension(552, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblagamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblagamaMouseClicked
        Agama agama = new Agama();
        agama.setVisible(true);
    }//GEN-LAST:event_lblagamaMouseClicked

    private void lblpekerjaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpekerjaanMouseClicked
        Pekerjaan pekerjaan = new Pekerjaan();
        pekerjaan.setVisible(true);
    }//GEN-LAST:event_lblpekerjaanMouseClicked

    private void lblshdrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblshdrtMouseClicked
        SHDRT shdrt = new SHDRT();
        shdrt.setVisible(true);
    }//GEN-LAST:event_lblshdrtMouseClicked

    private void lblpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpetugasMouseClicked
        Petugas petugas = new Petugas();
        petugas.setVisible(true);
    }//GEN-LAST:event_lblpetugasMouseClicked

    private void lbldesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldesaMouseClicked
        Desa desa = new Desa();
        desa.setVisible(true);
    }//GEN-LAST:event_lbldesaMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblagama;
    private javax.swing.JLabel lbldesa;
    private javax.swing.JLabel lblmenu;
    private javax.swing.JLabel lblpekerjaan;
    private javax.swing.JLabel lblpetugas;
    private javax.swing.JLabel lblshdrt;
    // End of variables declaration//GEN-END:variables
}
