/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Senoramadhani
 */
public class Menu extends javax.swing.JFrame {
    
    
    public Menu() {
        initComponents();
        tgljam();

    }
    public void tgljam(){
        int hari, bulan, tahun;
        GregorianCalendar date = new GregorianCalendar();
        String namabulan[] = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
        hari = date.get(Calendar.DAY_OF_MONTH);
        bulan = date.get(Calendar.MONTH);
        tahun = date.get(Calendar.YEAR);
        lbltgl.setText(hari+" "+namabulan[bulan]+" "+tahun);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblkematian = new javax.swing.JLabel();
        lblexport = new javax.swing.JLabel();
        lblkelahiran = new javax.swing.JLabel();
        lblpindah = new javax.swing.JLabel();
        lblkedatangan = new javax.swing.JLabel();
        lblmenu = new javax.swing.JLabel();
        lblwaktu = new javax.swing.JLabel();
        lbltgl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbltgl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        getContentPane().setLayout(null);

        lblkematian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/kematian.png"))); // NOI18N
        lblkematian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkematianMouseClicked(evt);
            }
        });
        getContentPane().add(lblkematian);
        lblkematian.setBounds(200, 120, 150, 50);

        lblexport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/export.png"))); // NOI18N
        lblexport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexportMouseClicked(evt);
            }
        });
        getContentPane().add(lblexport);
        lblexport.setBounds(20, 120, 150, 50);

        lblkelahiran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/kelahiran.png"))); // NOI18N
        lblkelahiran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkelahiranMouseClicked(evt);
            }
        });
        getContentPane().add(lblkelahiran);
        lblkelahiran.setBounds(20, 230, 150, 50);

        lblpindah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pindah.png"))); // NOI18N
        lblpindah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpindahMouseClicked(evt);
            }
        });
        getContentPane().add(lblpindah);
        lblpindah.setBounds(380, 120, 150, 50);

        lblkedatangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/kedatangan.png"))); // NOI18N
        lblkedatangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkedatanganMouseClicked(evt);
            }
        });
        getContentPane().add(lblkedatangan);
        lblkedatangan.setBounds(200, 230, 150, 50);

        lblmenu.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmenu.setText("Menu");
        getContentPane().add(lblmenu);
        lblmenu.setBounds(0, 0, 550, 42);

        lblwaktu.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblwaktu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblwaktu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logout.png"))); // NOI18N
        lblwaktu.setToolTipText("");
        lblwaktu.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblwaktu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblwaktuMouseClicked(evt);
            }
        });
        getContentPane().add(lblwaktu);
        lblwaktu.setBounds(480, 20, 50, 50);

        lbltgl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbltgl.setText("....................");
        getContentPane().add(lbltgl);
        lbltgl.setBounds(20, 30, 140, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/master.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 230, 150, 50);

        lbltgl1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbltgl1.setText("....................");
        getContentPane().add(lbltgl1);
        lbltgl1.setBounds(20, 30, 140, 15);

        setSize(new java.awt.Dimension(566, 379));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblkematianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkematianMouseClicked
        Kematian kematian = new Kematian();
        kematian.setVisible(true);
    }//GEN-LAST:event_lblkematianMouseClicked

    private void lblexportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexportMouseClicked
        Export export = new Export();
        export.setVisible(true);
    }//GEN-LAST:event_lblexportMouseClicked

    private void lblkelahiranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkelahiranMouseClicked
        Kelahiran kelahiran = new Kelahiran();
        kelahiran.setVisible(true);
    }//GEN-LAST:event_lblkelahiranMouseClicked

    private void lblkedatanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkedatanganMouseClicked
        Kedatangan kedatangan =  new Kedatangan();
        kedatangan.setVisible(true);
    }//GEN-LAST:event_lblkedatanganMouseClicked

    private void lblpindahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpindahMouseClicked
        Pindah pindah =  new Pindah();
        pindah.setVisible(true);
    }//GEN-LAST:event_lblpindahMouseClicked

    private void lblwaktuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblwaktuMouseClicked
        Login login =  new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblwaktuMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Master master =  new Master();
        master.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblexport;
    private javax.swing.JLabel lblkedatangan;
    private javax.swing.JLabel lblkelahiran;
    private javax.swing.JLabel lblkematian;
    private javax.swing.JLabel lblmenu;
    private javax.swing.JLabel lblpindah;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JLabel lbltgl1;
    private javax.swing.JLabel lblwaktu;
    // End of variables declaration//GEN-END:variables
}
